config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'application#root'
  get '/home', to: 'application#index'
  get '/about', to: 'application#about'

  get '/create_account', to: 'users#new'
  get '/sign_in', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy'

  get '/my_account', to: 'users#my_account'

  get '/cancel', to: 'wins#cancel'
  post '/filter', to: 'wins#filter'
  get '/reset_filter', to: 'wins#reset_filter'

  resources :users do
    resources :wins
  end
end

app/models/win.rb
# frozen_string_literal: true

# The Win model represents an individual accomplishment belonging to a User.
class Win < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :description, presence: true, length: { minimum: 3 }
  validates :category, presence: true

  scope :in_range, lambda { |start_date, end_date|
    where('accomplished_date >= ? AND accomplished_date <= ?', start_date, end_date)
  }

  scope :in_category, ->(categories) { where(category: categories) }

  scope :contains_string, ->(string) { where('title LIKE ? OR description LIKE ?', "%#{string}%", "%#{string}%") }
end

app/controllers/wins_controller.rb
# frozen_string_literal: true

# WinsController class controls CRUD operations and filtering for Win objects
class WinsController < ApplicationController
  include Pagy::Backend
  include SessionMethods

  before_action :set_user
  before_action :set_win, only: %i[show edit update destroy]
  before_action :set_errors, only: %i[new edit]

  def index
    session[:current_page] = params[:page] || 1
    limit = 8
    filtered_wins = apply_filter(@user.wins)
    session[:total_filtered_wins] = filtered_wins.length

    @pagy, @wins = pagy(filtered_wins, limit:, size: 3)
  end

  # rubocop:disable Metrics/MethodLength, Metrics/AbcSize
  def create
    @win = @user.wins.build(win_params)

    if @win.valid?
      @win.save
      reset_win_form_values
      earliest_and_latest_win_dates(@user.wins)
      set_default_filter
      redirect_to user_win_path({ user_id: @user.id, id: @win.id }), notice: "#{@win[:title]} added!"
    else
      set_win_form_values
      flash[:errors] = @win.errors.full_messages
      redirect_to new_user_win_path
    end
  end
  # rubocop:enable Metrics/MethodLength, Metrics/AbcSize

  def edit
    session[:current_win_id] = @win.id
  end

  # rubocop:disable Metrics/MethodLength, Metrics/AbcSize
  def update
    edited_win = @user.wins.build(win_params)

    if edited_win.valid?
      @win.update(win_params)
      reset_win_form_values
      reset_current_win_id
      earliest_and_latest_win_dates(@user.wins)
      redirect_to user_win_path, notice: "#{@win.title} has been updated."
    else
      set_win_form_values
      flash[:errors] = edited_win.errors.full_messages
      redirect_to edit_user_win_path
    end
  end
  # rubocop:enable Metrics/MethodLength, Metrics/AbcSize

  def destroy
    @win.destroy
    earliest_and_latest_win_dates(@user.wins)
    redirect_to @user, notice: "#{@win.title} has been deleted."
  end

  def cancel
    reset_win_form_values
    @win = @user.wins.find(session[:current_win_id])
    reset_current_win_id
    redirect_to user_win_path({ user_id: @user.id, id: @win.id })
  end

  def filter
    set_custom_date_range
    set_sort_by
    set_custom_categories
    set_query
    redirect_to user_wins_path(@user)
  end

  def reset_filter
    set_default_filter
    redirect_to user_wins_path(@user)
  end

  private

  FIELDS = %w[title description category accomplished_date(1i) accomplished_date(2i) accomplished_date(3i)].freeze

  def set_win
    @win = @user.wins.find(params[:id])
  end

  def set_errors
    @errors = flash[:errors]
  end

  def win_params
    params.require(:win).permit(:title, :description, :category, :accomplished_date)
  end

  def filter_params
    params.permit(:sort_by, :query, :kudos, :learning, :milestone, :project, :other,
                  '[date_start(1i)]', '[date_start(2i)]', '[date_start(3i)]',
                  '[date_end(1i)]', '[date_end(2i)]', '[date_end(3i)]')
  end

  def set_win_form_values
    FIELDS.each { |field| session[field] = win_params[field] }
  end

  def reset_win_form_values
    FIELDS.each { |field| session[field] = nil }
  end

  def reset_current_win_id
    session[:current_win_id] = nil
  end

  def get_date_filter_values(field)
    [1, 2, 3].map { |num| filter_params["[#{field}(#{num}i)]"].to_i }
  end

  def set_custom_date_range
    %w[date_start date_end].each { |field| session[field] = Date.new(*get_date_filter_values(field)) }
  end

  def set_custom_categories
    session[:categories] = CATEGORIES.select { |category| filter_params[category] }
  end

  def set_sort_by
    session[:sort_by] = filter_params[:sort_by] == 'newest first' ? 'desc' : 'asc'
  end

  def set_query
    session[:query] = Win.sanitize_sql_like(filter_params[:query])
  end

  def set_default_filter
    session[:date_start] = session[:earliest_win_date]
    session[:date_end] = session[:latest_win_date]
    session[:categories] = CATEGORIES
    session[:sort_by] = 'desc'
    session[:query] = ''
  end

  def apply_filter(wins)
    wins.in_range(session[:date_start], session[:date_end])
        .in_category(session[:categories])
        .order(accomplished_date: session[:sort_by], title: :asc)
        .contains_string(session[:query])
  end
end

app/helpers/wins_helper.rb
# frozen_string_literal: true

# WinsHelper module includes logic used for displaying wins and prepopulating values in win forms
module WinsHelper
  def populate_date
    year, month, day = [session['accomplished_date(1i)'],
                        session['accomplished_date(2i)'],
                        session['accomplished_date(3i)']].map(&:to_i)
    is_valid_date = [year, month, day].none?(&:zero?)

    Date.new(year, month, day) if is_valid_date
  end

  def populate_sort_by
    session[:sort_by] == 'desc' ? 'newest first' : 'oldest first'
  end
end

app/views/wins/edit.html.erb
<%= form_with model: @win, url: user_win_path, method: :patch, local: true, class: "one-column" do |form| %>
  <h2>Edit Win</h2>
  <%= form.label :title %>
  <%= form.text_field :title, value: session[:title] || @win.title %><br>

  <%= form.label :description %>
  <%= form.text_area :description, value: session[:description] || @win.description %><br>

  <%= form.label :category %>
  <%= form.select :category, CATEGORIES, selected: session[:category] || @win.category %><br>

  <%= form.label "Date completed" %>
  <%= form.date_select :accomplished_date, options = { order: [:day, :month, :year], use_short_month: true, selected: populate_date || @win.accomplished_date, end_year: Date.today.year }  %><br>

  <%= form.submit %><br>
  <%= link_to "Cancel", cancel_path %>
<% end %>

app/views/wins/index.html.erb
<%= content_for :head do %>
  <%= javascript_import_module_tag "common" %>
<% end %>

<h2>My Wins</h2>

<menu id="filter-container" class="hide">
  <%= button_tag "✕", id: "close-filter-btn" %>

  <h3>Filter</h3>
  <%= form_with(url: filter_path, method: :post, id: "wins-filter") do |form| %>
    <fieldset id="date-filter">
      <%= form.label :from %>
      <%= form.date_select :date_start, options = { order: [:day, :month, :year], use_short_month: true, selected: Date.parse(session[:date_start]), start_year: Date.today.year - 5, end_year: Date.today.year } %>

      <%= form.label :to %>
      <%= form.date_select :date_end, options = { order: [:day, :month, :year], use_short_month: true, selected: Date.parse(session[:date_end]), start_year: Date.today.year - 5, end_year: Date.today.year } %>
    </fieldset>

    <fieldset id="sort-by-filter">
      <%= form.label :sort_by %>
      <%= form.select :sort_by, ['newest first', 'oldest first'], selected: populate_sort_by %>
    </fieldset>

    <fieldset id="category-filter">
      <%= form.label :category %>
      <% CATEGORIES.each do |category| %>
        <span class="checkbox-option">
          <%= check_box_tag(category, 1, session[:categories].include?(category)) %>
          <%= label_tag(category, category) %>
        </span>
      <% end %>
    </fieldset>

    <fieldset id="query-filter">
      <%= form.label :query, "Filter by keyword" %>
      <%= form.text_field :query %>
    </fieldset>

    <%= form.submit "Filter", id: "submit-filter-btn" %>
    <%= link_to "Reset", reset_filter_path, id: "reset-filter-btn" %>
  <% end %>
</menu>

<%= button_tag image_tag("filter-icon.png", class: "small-icon"), id: "open-filter-btn" %>

<section id="win-summary">
    <p>Results: <%= pluralize(session[:total_filtered_wins], "win") %></p>
    <p id="query-description"><% if session[:query].length > 1 %>Title or description include: "<%= session[:query] %>"<% end %></p>
    <%= button_to "+ Add win", new_user_win_path(@user), method: :get , id: "add-win-btn" %>
</section>

<section id="card-container">
  <% @wins.each do |win| %>
    <%= link_to user_win_path(id: win.id) do %>
    <article class="card <%= win.category %>">
      <div class="card-logo">
        <%= image_tag("card-icon-#{win.category}.png", alt: "profile icon", class: "medium-icon card-icon" ) %>
        <h4 class="card-category"><%= win.category %></h4>
      </div>
      <p class="card-date"><%= format_date(win.accomplished_date) %></p>
      <h3 class="card-title"><%= win.title %></h3>
    </article>
    <% end %>
  <% end %>
</section>

<%= pagy_nav(@pagy).html_safe %>

app/views/wins/new.html.erb
<%= form_with model: [ @user, @user.wins.build ], class: "one-column" do |form| %>
  <h2>Add a Win</h2>
  <%= form.label :title %>
  <%= form.text_field :title, value: session[:title], placeholder: "Must be at least 3 characters" %><br>

  <%= form.label :description %>
  <%= form.text_area :description, value: session[:description], placeholder: "Must be at least 3 characters" %><br>

  <%= form.label :category %>
  <%= form.select :category, CATEGORIES, include_blank: "Choose a category", selected: session[:category] %><br>

  <%= form.label "Date completed" %>
  <%= form.date_select(:accomplished_date, options = { order: [:day, :month, :year], use_short_month: true, selected: populate_date || Date.today, end_year: Date.today.year }) %><br>

  <%= form.submit %><br>
  <%= link_to "Cancel", user_path(@user) %>
<% end %>

app/views/wins/show.html.erb
<div class="one-column">
  <article class="card-detail <%= @win.category %>">
    <div class="card-detail-logo">
      <%= image_tag("card-icon-#{@win.category}.png", alt: "profile icon", class: "large-icon card-icon" ) %>
      <h4><%= @win.category %></h4>
    </div>
    
    <h3><%= @win.title %></h3>
    <p><%= @win.description %></p>
    <p><%= format_date(@win.accomplished_date) %></p>

    <menu>
      <%= link_to "Edit", edit_user_win_path %>
      <%= link_to "Delete", user_win_path,  data: {
                        turbo: true,
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure you want to delete this win?"
                      } %>
    </menu>
  </article>
</div>

<%= render "application/go_back" %>