config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'application#root'
  get '/home', to: 'application#index'
  get '/about', to: 'application#about'

  get '/create_account', to: 'users#new'
  get '/sign_in', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy'

  get '/my_account', to: 'users#my_account'

  get '/cancel', to: 'wins#cancel'
  post '/filter', to: 'wins#filter'
  get '/reset_filter', to: 'wins#reset_filter'

  resources :users do
    resources :wins
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application Controller
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def root
    redirect_to logged_in? ? user_path(session[:user_id]) : home_path
  end

  def logged_in?
    !!session[:user_id]
  end

  def authorized
    redirect_to sign_in_path unless logged_in?
  end

  def set_user
    @user = User.find(session[:user_id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# ApplicationHelper module includes methods for displaying masked passwords and dates
module ApplicationHelper
  def format_masked_password(length)
    '●' * length
  end

  def format_date(date)
    date.strftime('%d %b %Y')
  end
end

app/views/application/_errors.html.erb
<% if errors %>
  <div role="alert" class="flash" >
    <%= image_tag("clippy-icon.png", alt: "error icon", class: "medium-icon shake")%>
    <% if errors.length > 1 %>
      <ul>
        <% errors.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    <% else %>
      <p><%= errors.first %></p>
    <% end %>
  </div>
<% end %>

app/views/application/_go_back.html.erb
<nav>
  <%= link_to "Go back", 
    if session[:user_id]
      user_wins_path(user_id: session[:user_id], page: session[:current_page]) 
    else
      root_path
    end
  %>
</nav>

app/views/application/about.html.erb
<article class="one-column">
  <h2>About</h2>

  <h3>If you were up for a dream job or a big promotion, who would you nominate to be your hypeman?</h3>

  <p>Your boss? Your best friend? Or somebody else?</p>

  <p>When it comes to advocating for yourself, <em>the best person for the job is you</em>. No one knows the ins and outs, the scope, or the impact of your accomplishments as well as you do.</p>
  
  <p>But when you go to update your resumé or write a performance review, can you remember everything that you've done in the last quarter? The last year? The last few years?</p>

  <h3>Nguyen Streak is an app to track your wins.</h3>

  <p>Instead of digging through stacks of old emails, documents, and DMs, Nguyen Streak makes it easier to organize all your accomplishments in one place.</p>

  <ul>
    <li>Track your wins by date and category</li>
    <li>Add supporting details and stats</li>
    <li>Filter your wins by date</li>
  </ul>

  <h3>How do I pronounce 'Nguyen Streak'? </h3>
  <p id="card-content">It's pronounced <em>[win strēk]</em>.
</article>

<%= render "application/go_back" %>

app/views/application/index.html.erb
<p>Please <%= link_to "sign in", sign_in_path %> or <%= link_to "create an account", create_account_path %></p>