config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'application#root'
  get '/home', to: 'application#index'
  get '/about', to: 'application#about'

  get '/create_account', to: 'users#new'
  get '/sign_in', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy'

  get '/my_account', to: 'users#my_account'

  get '/cancel', to: 'wins#cancel'
  post '/filter', to: 'wins#filter'
  get '/reset_filter', to: 'wins#reset_filter'

  resources :users do
    resources :wins
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nguyen Streak</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield(:head) %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100..700;1,100..700&family=Urbanist:ital,wght@0,100..900;1,100..900&display=swap' %>
    <%= stylesheet_link_tag 'application.css' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div role="alert" class="flash" >
        <%= image_tag("success-icon.png", alt: "success icon", class: "medium-icon bounce")%>
        <p><%= flash[:notice] %></p>
      </div>
    <% end %>

    <%= render "application/errors", errors: @errors %>

    <header>
      <section id="title">
      <%= link_to root_path do %>
        <%= image_tag("laurels.png", alt: "laurels icon", class: "large-icon" ) %>
        <h1>Nguyen Streak</h1>
      <% end %>
      </section>

      <nav id="main-nav">
        <menu>
          <li><%= link_to "About", about_path %></li>   
          <% if logged_in? %>
            <div class="dropdown">
              <li id="profile-dropdown"><%= image_tag("profile-icon.png", alt: "profile icon", class: "small-icon" ) %><%= session[:username] %></li>   
              <ul class="dropdown-content">
                <li><%= link_to "My account", my_account_path %></li>
                <li><%= link_to "Sign out", sessions_path, data: {
                      turbo: true,
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure you want to sign out?"
                    } %></li> 
              </ul>
            </div>    
          <% else %>
            <li><%= link_to "Sign in", sign_in_path %></li>
          <% end %>
        </menu>
      </nav>
    </header>
  
    <main >
      <%= yield %>
    </main>
  </body>
</html>